version: 0.2

env:
  parameter-store:
    SSH_KEY: "/codebuild/qc-build-bot-rsa"
  variables:
    GO111MODULE: "on"

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY\n" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval `ssh-agent`
      - ssh-add ~/.ssh/id_rsa
      - git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
      - grep -v refmt go.sum > go.sum.mod && mv go.sum.mod go.sum
      - go mod vendor
      - ./scripts/download-golangci-lint.sh
  build:
    commands:
      - golangci-lint run
      - go test -mod=vendor ./... -tags=integration
