// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactions.proto

package chaintree

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetDataPayload struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataPayload) Reset()         { *m = SetDataPayload{} }
func (m *SetDataPayload) String() string { return proto.CompactTextString(m) }
func (*SetDataPayload) ProtoMessage()    {}
func (*SetDataPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_839702782e93e893, []int{0}
}
func (m *SetDataPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataPayload.Unmarshal(m, b)
}
func (m *SetDataPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataPayload.Marshal(b, m, deterministic)
}
func (dst *SetDataPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataPayload.Merge(dst, src)
}
func (m *SetDataPayload) XXX_Size() int {
	return xxx_messageInfo_SetDataPayload.Size(m)
}
func (m *SetDataPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataPayload proto.InternalMessageInfo

func (m *SetDataPayload) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetDataPayload) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetOwnershipPayload struct {
	Authentication       []string `protobuf:"bytes,1,rep,name=authentication,proto3" json:"authentication,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOwnershipPayload) Reset()         { *m = SetOwnershipPayload{} }
func (m *SetOwnershipPayload) String() string { return proto.CompactTextString(m) }
func (*SetOwnershipPayload) ProtoMessage()    {}
func (*SetOwnershipPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_839702782e93e893, []int{1}
}
func (m *SetOwnershipPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOwnershipPayload.Unmarshal(m, b)
}
func (m *SetOwnershipPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOwnershipPayload.Marshal(b, m, deterministic)
}
func (dst *SetOwnershipPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOwnershipPayload.Merge(dst, src)
}
func (m *SetOwnershipPayload) XXX_Size() int {
	return xxx_messageInfo_SetOwnershipPayload.Size(m)
}
func (m *SetOwnershipPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOwnershipPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SetOwnershipPayload proto.InternalMessageInfo

func (m *SetOwnershipPayload) GetAuthentication() []string {
	if m != nil {
		return m.Authentication
	}
	return nil
}

type CoinMonetaryPolicy struct {
	Maximum              uint64   `protobuf:"varint,1,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinMonetaryPolicy) Reset()         { *m = CoinMonetaryPolicy{} }
func (m *CoinMonetaryPolicy) String() string { return proto.CompactTextString(m) }
func (*CoinMonetaryPolicy) ProtoMessage()    {}
func (*CoinMonetaryPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_839702782e93e893, []int{2}
}
func (m *CoinMonetaryPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinMonetaryPolicy.Unmarshal(m, b)
}
func (m *CoinMonetaryPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinMonetaryPolicy.Marshal(b, m, deterministic)
}
func (dst *CoinMonetaryPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinMonetaryPolicy.Merge(dst, src)
}
func (m *CoinMonetaryPolicy) XXX_Size() int {
	return xxx_messageInfo_CoinMonetaryPolicy.Size(m)
}
func (m *CoinMonetaryPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinMonetaryPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_CoinMonetaryPolicy proto.InternalMessageInfo

func (m *CoinMonetaryPolicy) GetMaximum() uint64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

type EstablishCoinPayload struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MonetaryPolicy       *CoinMonetaryPolicy `protobuf:"bytes,2,opt,name=monetary_policy,json=monetaryPolicy,proto3" json:"monetary_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EstablishCoinPayload) Reset()         { *m = EstablishCoinPayload{} }
func (m *EstablishCoinPayload) String() string { return proto.CompactTextString(m) }
func (*EstablishCoinPayload) ProtoMessage()    {}
func (*EstablishCoinPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_839702782e93e893, []int{3}
}
func (m *EstablishCoinPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishCoinPayload.Unmarshal(m, b)
}
func (m *EstablishCoinPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishCoinPayload.Marshal(b, m, deterministic)
}
func (dst *EstablishCoinPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishCoinPayload.Merge(dst, src)
}
func (m *EstablishCoinPayload) XXX_Size() int {
	return xxx_messageInfo_EstablishCoinPayload.Size(m)
}
func (m *EstablishCoinPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishCoinPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishCoinPayload proto.InternalMessageInfo

func (m *EstablishCoinPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EstablishCoinPayload) GetMonetaryPolicy() *CoinMonetaryPolicy {
	if m != nil {
		return m.MonetaryPolicy
	}
	return nil
}

type MintCoinPayload struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MintCoinPayload) Reset()         { *m = MintCoinPayload{} }
func (m *MintCoinPayload) String() string { return proto.CompactTextString(m) }
func (*MintCoinPayload) ProtoMessage()    {}
func (*MintCoinPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_839702782e93e893, []int{4}
}
func (m *MintCoinPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintCoinPayload.Unmarshal(m, b)
}
func (m *MintCoinPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintCoinPayload.Marshal(b, m, deterministic)
}
func (dst *MintCoinPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintCoinPayload.Merge(dst, src)
}
func (m *MintCoinPayload) XXX_Size() int {
	return xxx_messageInfo_MintCoinPayload.Size(m)
}
func (m *MintCoinPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_MintCoinPayload.DiscardUnknown(m)
}

var xxx_messageInfo_MintCoinPayload proto.InternalMessageInfo

func (m *MintCoinPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MintCoinPayload) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Transaction struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload              *any.Any `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_839702782e93e893, []int{5}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Transaction) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*SetDataPayload)(nil), "chaintree.SetDataPayload")
	proto.RegisterType((*SetOwnershipPayload)(nil), "chaintree.SetOwnershipPayload")
	proto.RegisterType((*CoinMonetaryPolicy)(nil), "chaintree.CoinMonetaryPolicy")
	proto.RegisterType((*EstablishCoinPayload)(nil), "chaintree.EstablishCoinPayload")
	proto.RegisterType((*MintCoinPayload)(nil), "chaintree.MintCoinPayload")
	proto.RegisterType((*Transaction)(nil), "chaintree.Transaction")
}

func init() { proto.RegisterFile("transactions.proto", fileDescriptor_transactions_839702782e93e893) }

var fileDescriptor_transactions_839702782e93e893 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xc9, 0xf7, 0x5b, 0x5b, 0x3a, 0x95, 0x16, 0xd6, 0x22, 0x51, 0x10, 0x4a, 0x0e, 0xd2,
	0xd3, 0x16, 0xf4, 0x26, 0xf4, 0xe0, 0xcf, 0x5b, 0xb1, 0x6e, 0x3d, 0x79, 0x91, 0x69, 0x5c, 0x9b,
	0x85, 0xec, 0x6e, 0x48, 0x26, 0xea, 0xfe, 0xf7, 0x92, 0x4d, 0xd2, 0xfa, 0xe3, 0xe0, 0x6d, 0x5e,
	0x32, 0xf3, 0xde, 0x87, 0x7d, 0xc0, 0x28, 0x47, 0x53, 0x60, 0x4c, 0xca, 0x9a, 0x82, 0x67, 0xb9,
	0x25, 0xcb, 0xfa, 0x71, 0x82, 0xca, 0x50, 0x2e, 0xe5, 0xf1, 0xd1, 0xc6, 0xda, 0x4d, 0x2a, 0x67,
	0xfe, 0xc7, 0xba, 0x7c, 0x9d, 0xa1, 0x71, 0xf5, 0x56, 0x74, 0x01, 0xc3, 0x95, 0xa4, 0x1b, 0x24,
	0x5c, 0xa2, 0x4b, 0x2d, 0xbe, 0x30, 0x06, 0x9d, 0x0c, 0x29, 0x09, 0x83, 0x49, 0x30, 0xed, 0x0b,
	0x3f, 0xb3, 0x31, 0xec, 0xbd, 0x61, 0x5a, 0xca, 0xf0, 0xdf, 0x24, 0x98, 0xee, 0x8b, 0x5a, 0x44,
	0x73, 0x38, 0x58, 0x49, 0xba, 0x7f, 0x37, 0x32, 0x2f, 0x12, 0x95, 0xb5, 0x06, 0xa7, 0x30, 0xc4,
	0x92, 0x12, 0x69, 0x48, 0xc5, 0x58, 0x11, 0x85, 0xc1, 0xe4, 0xff, 0xb4, 0x2f, 0x7e, 0x7c, 0x8d,
	0x38, 0xb0, 0x6b, 0xab, 0xcc, 0xc2, 0x1a, 0x49, 0x98, 0xbb, 0xa5, 0x4d, 0x55, 0xec, 0x58, 0x08,
	0x3d, 0x8d, 0x1f, 0x4a, 0x97, 0xda, 0x13, 0x74, 0x44, 0x2b, 0xa3, 0x1c, 0xc6, 0xb7, 0x05, 0xe1,
	0x3a, 0x55, 0x45, 0x52, 0x1d, 0x7e, 0x01, 0x36, 0xa8, 0x65, 0x0b, 0x5c, 0xcd, 0xec, 0x0e, 0x46,
	0xba, 0xf1, 0x7d, 0xce, 0xbc, 0xb1, 0x47, 0x1f, 0x9c, 0x9d, 0xf0, 0xed, 0xb3, 0xf0, 0xdf, 0xe9,
	0x62, 0xa8, 0xbf, 0xe9, 0x68, 0x0e, 0xa3, 0x85, 0x32, 0xf4, 0x57, 0xdc, 0x21, 0x74, 0x51, 0xdb,
	0xd2, 0x90, 0x4f, 0xe9, 0x88, 0x46, 0x45, 0x0f, 0x30, 0x78, 0xdc, 0x35, 0x53, 0x9d, 0x92, 0xcb,
	0xb6, 0xa7, 0xd5, 0xcc, 0x38, 0xf4, 0x1a, 0xe7, 0x86, 0x70, 0xcc, 0xeb, 0xb6, 0x78, 0xdb, 0x16,
	0xbf, 0x34, 0x4e, 0xb4, 0x4b, 0x57, 0x83, 0xa7, 0x5d, 0xb1, 0xeb, 0xae, 0xdf, 0x39, 0xff, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x0d, 0x65, 0x03, 0xc4, 0x00, 0x02, 0x00, 0x00,
}
